version: "3.9"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./src:/src:rw
    env_file:
      - .env
    command:
      - /bin/bash
      - -c
      - |
        foreman start release
        foreman start web
    environment:
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1

  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data,delegated
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
