api:
  auth:
    devise_jwt_secret_key: <%= ENV.fetch("DEVISE_JWT_SECRET_KEY", "") %>
system:
  db:
    host: <%= ENV.fetch("DATABASE_HOST", "") %>
    user: <%= ENV.fetch("DATABASE_USER", "") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  default_email: <%= ENV.fetch("DEFAULT_EMAIL", "") %>
  host: <%= ENV.fetch("HOST", "") %>
  port: <%= ENV.fetch("PORT", "") %>
  rails_env: <%= ENV.fetch("RAILS_ENV", "") %>
